# Generated by Django 4.1.3 on 2022-11-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(choices=[('мужской', 'Male'), ('женский', 'Female')], default='мужской', max_length=50),
        ),
    ]
