# Generated by Django 4.1.3 on 2022-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_subscriber_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(choices=[('MALE', 'мужской'), ('FEMALE', 'женский')], default='MALE', max_length=50, verbose_name='Пол'),
        ),
    ]
