# Generated by Django 4.1.3 on 2022-11-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_subscriber_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberMailingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.mailing')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', through='mail.SubscriberMailingRelation', to='mail.subscriber'),
        ),
    ]
