# Generated by Django 4.1.3 on 2022-11-18 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_mail_subscribermailrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='SubscriberMailingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True)),
                ('read_at', models.DateTimeField(blank=True)),
                ('mail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mail.mailing')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.RemoveField(
            model_name='subscribermailrelation',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='subscribermailrelation',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='SubscriberMailRelation',
        ),
        migrations.AddField(
            model_name='subscribermailingrelation',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.subscriber'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', through='mail.SubscriberMailingRelation', to='mail.subscriber'),
        ),
    ]
