# Generated by Django 4.1.3 on 2022-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribermailingrelation',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscribermailingrelation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
