# Generated by Django 4.1.3 on 2022-11-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_subscribermailingrelation_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='content',
            field=models.TextField(blank=True, help_text='Теги добавляем в двойных фигурных скобках \\{\\{\\}\\}: firstname - имя, lastname - фамилия, birthday - день рождения', verbose_name='Контент'),
        ),
    ]
