# Generated by Django 4.1.3 on 2022-11-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_mailing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
    ]
