# Generated by Django 4.1.3 on 2022-11-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_alter_mailing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mailing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.mailing'),
        ),
    ]
