# Generated by Django 4.1.3 on 2022-11-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_alter_mailing_options_subscriber_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='mailing',
            new_name='is_mailing',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mailing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing', to='mail.mailing'),
        ),
    ]
